apiVersion: v1
kind: Service
metadata:
  name: atmos-weather
spec:
  type: {{ .Values.service.type }}

  selector:
    app: atmos-weather

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http