replicaCount: 1

image:
  repository: ritchiekyin/atmos-weather
  tag: "sha-92f6686abde1617cc0fbd1449a9c16b0e880e7ad"
  pullPolicy: IfNotPresent

imagePullSecret:
  name: dockerhub-pull

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

vault:
  enabled: true
  role: atmos-weather
  secretPath: secret/data/atmos-weather