apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-dockerhub
  namespace: weather-lab

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: weather-lab
spec:
  address: http://vault.vault.svc.cluster.local:8200

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: dockerhub
  namespace: weather-lab
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes

  kubernetes:
    role: dockerhub-vso
    serviceAccount: vso-dockerhub

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dockerhub-pull
  namespace: weather-lab
spec:
  vaultAuthRef: dockerhub
  type: kv-v2
  mount: secret
  path: dockerhub
  refreshAfter: 30s

  destination:
    name: dockerhub-pull
    create: true
    type: kubernetes.io/dockerconfigjson